services:
  # metafi-bridge-be:
  #   container_name: metafi-bridge-be
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3002:3000'
  #   environment:
  #     TOKEN_VERIFY_DURATION_TIME: 86400
  #     MODE: DEV
  #     DB_NAME: metafi-bridge
  #     DB_USER: postgres
  #     DB_PASSWORD: postgres
  #     DB_HOST: postgresdb
  #     DB_PORT: 5432
  #     JTW_PRIVATE_PATH_FILE: app/keys/auth.private.key
  #     JTW_PUBLIC_PATH_FILE: app/keys/auth.public.key
  #   volumes:
  #     - .:/app
  #   restart: unless-stopped
  postgresdb:
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: metafi-bridge
