version: '3.8'

services:
  app:
    container_name: launchpad_api_container
    image: roster90/metafi-launchpad-api:0.1.0
    ports:
      - "80:3001"
    environment:
      NODE_ENV: production
      DB_NAME: 
      DB_USER: 
      DB_PASSWORD: 
      DB_HOST: 152.42.240.49
      DB_PORT: 5432
      SOLAN_MODE: mainnet
      TOKEN_VERIFY_DURATION_TIME: 86400
      JTW_PRIVATE_PATH_FILE: app/auth.private.key
      JTW_PUBLIC_PATH_FILE: app/auth.public.key
    volumes:
      - .:/app
    restart: unless-stopped