

##login
POST   http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
    "email":"thoains@gmail.com",
    "password": "123456"
}


### get all
GET  http://localhost:3000/api/ido HTTP/1.1
content-type: application/json





###  get detail by id
GET  http://localhost:3000/api/ido/6 HTTP/1.1
content-type: application/json


###  get detail by contract
GET  http://localhost:3000/api/ido/detail/AMcMZPGoDqq8toy5D48hXNwBu7nzyEV5xrwHawmrcj3g HTTP/1.1
content-type: application/json

##### require admin ######

###  Create
POST http://localhost:3000/api/ido HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInZlcnNpb24iOjAsImlhdCI6MTcxOTQ3ODgzMCwiZXhwIjoxNzE5NTY1MjMwfQ.hVj9yjlZnw3B7c7c2QBy_RmvJ4jVaEuAtde2x0cjXu8uk8qfiN4nShsLSBokqpPLb00-1daujXkJE7erQ0HC1CCGe6QXmli_4LRWw0yHKq4cox7yYCM_ZTmq95rO93GWtNwsHRtCLAirSBIn3da6X-JBaKUlvHho41aqB7gkp3Ei8xXfc9OXDuLjp-2EsAjLUi1IJcAB9WB1iuvmtx8DmaGiVu9rIQ34Fi9HxowAQDFMmQEsz2WCAHdwrRSPLTPsMouITRH94xN3p6fz965gjyk-54Ind1Hfu3uV5tQdtqfEpAIHGzPnoahvggjicDErTxcss0Z15hZOdHfmkXT8mw

{
	"contract": "TBA",
    "contractVersion": "1.0",
    "raiseTokenAddress": "BUJST4dk6fnM5G3FnhTVc3pjxRJE7w2C5YL9XgLbdsXW",
    "raiseTokenDecimals": 6,
    "raiseTokenSymbol": "USDC",
    "releaseTokenAddress":"TBA",
    "releaseTokenSymbol": "BLST",
    "releaseTokenDecimals": 9,
    "isPrivate": true,
    "rate": 1000000,
    "description": "TEST 2",
    "telegram": "https://t.me/Blast_Fi",
    "logo": "https://i.ibb.co/HXR58JW/BD20.jpg",
    "medium": "https://medium.com/test",
    "name": "TEST 2",
    "totalSupply": 1000000,
    "twitter": "https://twitter.com/Blast_Fi",
    "website": "https://blastfi.io/",
    "youtube":"",
    "state": "P"
}
###  Update by id

Put  http://localhost:3000/api/ido/6 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInZlcnNpb24iOjAsImlhdCI6MTcxODI0NzEzNiwiZXhwIjoxNzE4MzMzNTM2fQ.S71jwIhMfRrMZEwc8MZf3k3zJr5t-SXz8fiBsf_8Y0zE0iKp7gTKuLo_MHtu-dTjp1s__1wz1jveSGkZJss3um96ttaSTOlrEsKEzJhI6nkvE3lE-aN2XOsG3-stOyc2l2ca7S2x0v_Cr4zhtyjcznr0hFA6bduAblZIZSboseutWaSPSvP7FoyN0HKYR3wt6Bw7Ui9m_qPK1qRMaM7WzS1jdvHLdIyrrCpJbMGFicxXn_Atzc4Gvo0Q00A4n2ztCKw0LgC5xDq2FaqIpCRCv2FGds6CyF9c4nWIbrlQUc4-maDdGDRn684QAAazJQeyd4a_9GUZIu3LGaWY1vqMtA
{
    "name": "Project 1",
    "description": "Project 1",
    "contract": "AMcMZPGoDqq8toy5D48hXNwBu7nzyEV5xrwHawmrcj3g",
}


###  PUT

DELETE  http://localhost:3000/api/ido/6 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInZlcnNpb24iOjAsImlhdCI6MTcxODI0NzEzNiwiZXhwIjoxNzE4MzMzNTM2fQ.S71jwIhMfRrMZEwc8MZf3k3zJr5t-SXz8fiBsf_8Y0zE0iKp7gTKuLo_MHtu-dTjp1s__1wz1jveSGkZJss3um96ttaSTOlrEsKEzJhI6nkvE3lE-aN2XOsG3-stOyc2l2ca7S2x0v_Cr4zhtyjcznr0hFA6bduAblZIZSboseutWaSPSvP7FoyN0HKYR3wt6Bw7Ui9m_qPK1qRMaM7WzS1jdvHLdIyrrCpJbMGFicxXn_Atzc4Gvo0Q00A4n2ztCKw0LgC5xDq2FaqIpCRCv2FGds6CyF9c4nWIbrlQUc4-maDdGDRn684QAAazJQeyd4a_9GUZIu3LGaWY1vqMtA